sudo: required

branches:
  only:
    - master
    - dev

language: node_js

node_js:
  - "stable"

install:
  - npm install -g travis-ci-cloudfront-invalidation
  - npm install

cache:
  directories:
    - node_modules

script:
  - npm run test
  - npm run build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "chive-app-prod"
  local_dir: build
  skip_cleanup: true
  region: "us-east-1"
  on:
    branch: master

after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_ID -s $AWS_SECRET_ID -c $CLOUDFRONT_DIST_ID_PRODUCTION -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
