sudo: required

branches:
  only:
    - master
    - dev

language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

script:
  - npm run build
  - npm run test

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "chive-app-prod"
  skip_cleanup: true
  region: "us-east-1"
  on:
    branch: master
