sudo: required

language: node_js

node_js:
  - "stable"

install:
  - npm install -g travis-ci-cloudfront-invalidation
  - npm install

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: test
      script:
        - npm run test

    - stage: deploy-demo
      if: branch = demo

      script:
        - npm run build

      deploy:
        - provider: s3
          access_key_id: $AWS_ACCESS_KEY_ID
          secret_access_key: $AWS_SECRET_ACCESS_KEY
          bucket: "chive-app-demo"
          local_dir: build
          skip_cleanup: true
          region: "us-west-1"

      after_deploy:
        - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_ID -s $AWS_SECRET_ID -c $CLOUDFRONT_DIST_ID_DEMO -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST

    - stage: deploy-prod
      if: branch = master

      script:
        - npm run build

      deploy:
        - provider: s3
          access_key_id: $AWS_ACCESS_KEY_ID
          secret_access_key: $AWS_SECRET_ACCESS_KEY
          bucket: "chive-app-prod"
          local_dir: build
          skip_cleanup: true
          region: "us-west-1"

      after_deploy:
        - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_ID -s $AWS_SECRET_ID -c $CLOUDFRONT_DIST_ID_PRODUCTION -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
